### ISSUE TITLE
Collate all wiki to one place

### ISSUE THREAD

**Issue by nemaniarjun** [AIcrowd/AIcrowd#1000]
We have a lot of information hidden away in private wikis, its time to collate them all into one place
A private wiki for sensitive info and public if otherwise.

**Comment by nemaniarjun** [comment]
What is the right place to put it where it will be accessible by all the right parties? @spMohanty

**Comment by spMohanty** [comment]
@nemaniarjun : I would ideally want to put it all here : https://github.com/AIcrowd/AIcrowd-private-wiki

Please feel free to re-organize as you seem fit.

**Comment by skbly7** [comment]
Closing this issue from public tracker. This activity is already happening for documentation internally.
