### ISSUE TITLE
Non numeric fields in the meta params will break the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#1010]
If any non numberic fields are used in the meta params, which are to be rendered on the leaderboard, then it will break the leaderboard because of this : 

https://github.com/AIcrowd/AIcrowd/blob/master/app/concepts/leaderboard/cells/table_row.rb#L32

The precision drop expects a `.to_f` conversion for all the values.

**Comment by skbly7** [comment]
This was refactored couple of months back, to use `-` if `to_f` fails, closing it.
