### ISSUE TITLE
"Invite member" button should be hidden when not relevant

### ISSUE THREAD

**Issue by MasterScrat** [AIcrowd/AIcrowd#1014]
The button "Invite member" shows up even if the user is not part of the team, or not logged in. IMO there is no reason for the button to be visible in these situations.

<img width="488" alt="Screenshot 2019-10-04 at 12 22 54" src="https://user-images.githubusercontent.com/140592/66201448-aee7df00-e6a3-11e9-8f3f-5f2199b05a5b.png">

**Comment by skbly7** [comment]
Thanks @MasterScrat for reporting it to us.
