### ISSUE TITLE
Potential problem in leaderboard sorting logic

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1018]
I come across the leaderboard which was rendering 6th rank below the 7th. 
Attached is the screenshot, looks like some problem with rendering logic.

Link: https://www.aicrowd.com/challenges/neurips-2019-disentanglement-challenge/leaderboards
![image](https://user-images.githubusercontent.com/3490586/67363698-9294df00-f58b-11e9-96ae-109b3994686a.png)

**Comment by nemaniarjun** [comment]
Fixed in 1fb56f94626a29ffa0efd676dfca9c408610472f
