### ISSUE TITLE
CLEF: Messed up participants view

### ISSUE THREAD

**Issue by ieggel** [AIcrowd/AIcrowd#1034]
@nemaniarjun 

The view /challenges/<challenge>/clef_task view is messed up. This is the view that gets rendered when clicking on the participants tab on the challenge page. Maybe this happened when you cleaned the code.

Have a look here:

![image](https://user-images.githubusercontent.com/9192090/68756031-c18df600-0609-11ea-86c0-c1a9e95a05dc.png)

Could you please fix it? Maybe it would also be a good idea to also make the avatars smaller and have all the other info in a single line next to the avatar. Would that be possible?

**Comment by nemaniarjun** [comment]
https://aicrowd-design.netlify.com/
We have templates here, we can copy the html from there which suits the right representation.

**Comment by ieggel** [comment]
@nemaniarjun 
I found the bug:

You modified this line from:
```html
<i aria-hidden="true" class="fa fa-file-pdf-o fa-2x"></i>
```

to:
```html
<i aria-hidden="true" class="fa fa-file-pdf-o fa-2x"/>
```
It seems that the <i> tag cannot be self-closing.

I'll correct this now. Will also try to make this view a bit more appealing.
