### ISSUE TITLE
404 error during new user account creation in AIcrowd.com

### ISSUE THREAD

**Issue by DebalB** [AIcrowd/AIcrowd#1053]
I recently got a 404 Page not found error while trying to create my new account at AIcrowd.com
Steps followed as under:
1. Created login credentials under new user sign up
2. Received confirmation email and clicked on link to confirm my account.
3. Confirmation page shows a button to authorize Gitlab, clicked on same button.
4. Got an HTML page with 404 not found error printed.
5. Pressed back button in browser and clicked the authorize button again. No issues this time.
![AIcrowdLoginScreenIssue](https://user-images.githubusercontent.com/22232137/71958387-2f275e80-3216-11ea-9017-f1402412ed89.JPG)

**Comment by nemaniarjun** [comment]
Unable to reproduce. We should either A: remove this view or B: update to show AIcrowd Gitlab instead of crowdAI gitlab. Link to view: https://github.com/AIcrowd/AIcrowd/blob/master/app/views/doorkeeper/authorizations/new.html.erb

**Comment by nemaniarjun** [comment]
@masterscrat I think you faced this issue as well? 
@piotrekpasciak did you as well?

**Comment by MasterScrat** [comment]
I didn't face a 404, just an oversized Gitlab message:

<img width="1792" alt="Screenshot 2020-01-21 at 23 30 04" src="https://user-images.githubusercontent.com/140592/73020260-91db4580-3e25-11ea-9a13-4dd24cb71514.png">

The workflow worked fine for me apart from this design problem (yesterday, on January 21st 2020).

**Comment by spMohanty** [comment]
The text should also be update 👼

**Comment by nemaniarjun** [comment]
Do we need the authorization? @Shivam from gitlab end?

**Comment by skbly7** [comment]
Yes, this page is needed for login flow for Gitlab.

The text needed to be updated here:
https://github.com/AIcrowd/AIcrowd/blob/f1f5911b59ea75a7f02e73d298a2d872e0dcab12/app/views/doorkeeper/authorizations/new.html.erb

**Comment by nemaniarjun** [comment]
GitLab Auth page has been updated.
