### ISSUE TITLE
Pipeline should check robocop style adherence

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1064]
Given we have done heavy work in PR #1057 to improve codes' health. 

To ensure, we don't end up doing same mistakes, lets introduce checks in pipeline for auto-linting or rejecting code not linted properly.

**Comment by nemaniarjun** [comment]
https://github.com/marketplace/actions/rubocop-checks

**Comment by piotrekpasciak** [comment]
I've been using mostly CodeClimate and was happy about this tool:
https://www.google.com/search?q=github+codeclimate&oq=github+codeclimate&aqs=chrome..69i57j69i64.3887j0j7&sourceid=chrome&ie=UTF-8

**Comment by nemaniarjun** [comment]
I have also heard great things about code climate. Let's go with that.

**Comment by nemaniarjun** [comment]
This is fixed and part of our CI
