### ISSUE TITLE
Discourse related error handling

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1065]
Due to the nature of how Discourse is added in our rails codebase, it ends up having 500 error for multiple reasons, which include:

- category doesn't exist
- category name is too large for discourse to handle (as we have no limit on competition length or having longer length allowed)
- discourse is down (hypothetically it will cause 500 as well)
- etc..

We need proper fix for this. Worst case/Atleast, try/catch block which hide the discussion link on challenges page when discourse is causing any error.

**Comment by piotrekpasciak** [comment]
@skbly7 Fix for this issue is already on staging.

**Comment by nemaniarjun** [comment]
Closing issue as already completed.
