### ISSUE TITLE
Graphs Implementation  

### ISSUE THREAD

**Issue by nemaniarjun** [AIcrowd/AIcrowd#1143]
We want to implement graphs for things like challenge statistics. 

Method 1: Use chartkick (https://chartkick.com/) 
- Ruby based implementation

Supports: [Charts.js](https://www.chartjs.org/docs/), [Google Charts](https://developers.google.com/chart/interactive/docs/gallery), [Highcharts](https://api.highcharts.com/highcharts)

Pros:
- Easy to use "Create beautiful JavaScript charts with one line of Ruby"
- Custom Built for rails
- Already being used in Blazer setup 
- Works with [Groupdate](https://github.com/ankane/groupdate) (also part of blazer used for generating date queries )
- Ruby based implementation

Cons:
- D3.js seems to be more powerful for things beyond charts and graphs

Method 2: Use [D3.js](https://d3js.org/)
- JS based implementations 

Pros:
- Extremely powerful and allows to create much more than simple graphs
- More complex than chartkick but still easy to use
- [Cool](https://observablehq.com/@d3/zoom-to-bounding-box), [Cool](https://bl.ocks.org/mbostock/1345853) and [Interactively Cool](https://observablehq.com/@d3/brushable-scatterplot?collection=@d3/d3-brush)

Cons: 
- Need to pass data from rails -> js (using json templating or api endpoints)

Method 3: Use Groupdate for data endpoints + D3.js
Example for data endpoint:  
```ruby
class ChartsController < ApplicationController
  def completed_tasks
    render json: Task.group_by_day(:completed_at).count
  end
end
```

@skbly7 can you please add more details to this based on your experience with D3.js and the tradeoffs between ruby/rails vs js based implementation.

**Comment by nemaniarjun** [comment]
@skbly7 @piotrekpasciak @alkeshrails @spMohanty

**Comment by nemaniarjun** [comment]
Using d3 will allow us to have a lot of fun with the submissions and how we display submissions / results.

**Comment by skbly7** [comment]
I don't have any bias as such, but in case d3.js have the potential for cooler + vast rendering possibilities (lot of examples) I will like to go ahead with it.

This is assuming both have similar/equal dev efforts requirements.

**Comment by spMohanty** [comment]
I would go with chartkick for now.
D3.js is cool and powerful, agree. But we will have to do all the data plumbing to efficiently transport data from the backend to the front end, and for some visualizations this might be a lot of data, and we will end up reinventing the wheel when we could just reuse the best practices from chartkick. 

The supported visualizations from chartkick can help us roll out quite powerful visualizations already, and for more advanced visualizations we can consider d3.js in the future after gaining some experience with the internals of chartkick first in a safe environment where we can prototype things much faster.

**Comment by skbly7** [comment]
We went ahead with ChartKick and the feature is now live as "Challenge Insights" and rendering on user profile pages, closing this discussion.

In case we need something more powerful in the future, we can resume this discussion.
