### ISSUE TITLE
Plots on Challenge Insights page do not have Axis Labels

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#1213]
<img width="1293" alt="Screenshot 2020-03-08 at 19 29 26" src="https://user-images.githubusercontent.com/1581312/76168808-31a12880-6173-11ea-912f-91a7e782632c.png">

Both the plots do not have X and Y axis labels, which might be confusing for someone when they land on the page.

**Comment by nemaniarjun** [comment]
This needs discussion, @skbly7 suggested they were not needed during the review stage.

**Comment by spMohanty** [comment]
Well, it was confusing to me when I landed on the page. So I guess it might be confusing to others too.

Also for the Score plots, I would actually use the Primary/Secondary Score name (that we use on the leaderboard) as the Y-axis and X-axis can be time.

**Comment by piotrekpasciak** [comment]
This looks to be implemented already.
![Screenshot 2020-04-28 at 21 45 16](https://user-images.githubusercontent.com/9438445/80533313-b5baa400-899d-11ea-8cbc-5629d34b6f12.png)
