### ISSUE TITLE
"View Submissions" button on leaderboard is not consistent

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#1215]
Some submissions on the leaderboard do not have a "View Submissions" button.

<img width="1292" alt="Screenshot 2020-03-09 at 10 29 21" src="https://user-images.githubusercontent.com/1581312/76199916-00ffd400-61f1-11ea-9b87-bc82de7f0a32.png">

**Comment by piotrekpasciak** [comment]
@spMohanty @shivam This is already deployed to production
