### ISSUE TITLE
Add a hashtag to category rendering ?

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#1220]
Should we add a hash to the tags, so that they are more apparent as tags/categories ?

For example : "#reinforcement-learning" instead of "reinforcement-learning", we can probably do this only during the rendering. But from the UX point of view, its much more apparent then that this is a tag.

Thoughts @skbly7  ?

**Comment by skbly7** [comment]
Sure, I think that makes sense. We were considering the feature in-middle of "Category" / "Tags" causing not to go ahead with hashtag thing earlier.

But based on developments over the last few days, I feel more comfortable treating them as tags and have UX modifications accordingly. I will include it in category design improvement discussion.

**Comment by piotrekpasciak** [comment]
@skbly7 @spMohanty 
This looks to be already deployed to production.
