### ISSUE TITLE
Time to close the round shows HTML entities

### ISSUE THREAD

**Issue by jyotishp** [AIcrowd/AIcrowd#1225]
The time for the round to close shown beside the round name on the challenge pages contains HTML entities.
![2020-03-11-021903_353x75_scrot](https://user-images.githubusercontent.com/19331201/76358248-30bcf200-633f-11ea-94b5-423d25aaf077.png)

**Comment by piotrekpasciak** [comment]
@jyotishp This should be already. handled by:
https://github.com/AIcrowd/AIcrowd/pull/1341
