### ISSUE TITLE
Edit Challenge Button in the admin section

### ISSUE THREAD

**Issue by ayushshivani** [AIcrowd/AIcrowd#1236]
We do not have edit challenge option in the challenges section of the admin.

**Comment by skbly7** [comment]
We need to add edit button in the active admin, which redirect to respective challenges' edit page i.e. /challenges/<name>/edit

**Comment by piotrekpasciak** [comment]
@ayushshivani  @skbly7 
As far I know this is already deployed to production.
Link to PR:
- https://github.com/AIcrowd/AIcrowd/pull/1369

**Comment by piotrekpasciak** [comment]
@ayushshivani  @skbly7 
As far I know this is already deployed to production.
Link to PR:
- https://github.com/AIcrowd/AIcrowd/pull/1369
