### ISSUE TITLE
Improve load more/pagination across website

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1255]
We need to come up with an improved version of pagination, the current one is causing pain to users by clicking load more many times.

(suggested by @debalb here: https://github.com/AIcrowd/AIcrowd/issues/1144#issuecomment-588267892)

**Comment by piotrekpasciak** [comment]
We could implement lazy loading functionality. When user scrolls down we would automatically load additional records.

**Comment by skbly7** [comment]
Implemented by https://github.com/AIcrowd/AIcrowd/pull/1425
