### ISSUE TITLE
Discourse integration shouldn't run/fail silently when discourse env variables aren't set or not working

### ISSUE THREAD

**Issue by skbly7** [AIcrowd/AIcrowd#1278]
Refer: https://github.com/AIcrowd/AIcrowd/pull/1267/files#r395989224

There are multiple issues that came in the previous week in the dev environment when discourse-related variables are not set or wrongly set. We need to go through the code as part of this issue and make sure necessary checks are in place, so those errors are always handled properly, and dev setup (or any other) doesn't break. 

This includes the chances when production discourse is down and production website may break if so it should fail silently (with message wherever discourse blocks are) and notification to admins, etc

**Comment by piotrekpasciak** [comment]
<img width="1397" alt="Screenshot 2020-03-21 at 13 59 17" src="https://user-images.githubusercontent.com/9438445/77226938-58505d80-6b7c-11ea-8ab1-3723196be430.png">
<img width="1397" alt="Screenshot 2020-03-21 at 13 58 58" src="https://user-images.githubusercontent.com/9438445/77226940-5b4b4e00-6b7c-11ea-8e21-5e25afc12cad.png">

**Comment by piotrekpasciak** [comment]
@skbly7 Discourse Integration is disabled without ENV variables. Take a look on screenshots above.

**Comment by skbly7** [comment]
But then how the above scenerio i.e. @spMohanty and @alkeshrails faced can happen? I don't think their local setup have Discourse integration. Can you check an idea of their env variables so we can replicate or test.

**Comment by piotrekpasciak** [comment]
@skbly7 Didn't you assume that participant will be always present in this piece of code?
https://github.com/AIcrowd/AIcrowd/commit/9fa1fd9341b8314a5ecd0f05706e3ff601154bd9#diff-1016741f5705be0078d8629ba7ade681R6-R17

**Comment by piotrekpasciak** [comment]
Sometimes participant from Discourse won't be present in our database.

**Comment by skbly7** [comment]
Yup, because this code is being called only where participant objects are being iterated i.e. this file. 
https://github.com/AIcrowd/AIcrowd/blob/master/app/views/shared/discourse/_topics_list.html.erb

I assume their local env don't have Discourse setup in which case their landing page should have never called this partial.

**Comment by piotrekpasciak** [comment]
Not every topic will have `participant` present because we don't have:
- Discourse admin users in local / staging databases.
- Discourse users created from other developers development setups or staging setup

**Comment by skbly7** [comment]
> Sometimes participant from Discourse won't be present in our database.

Sure, seems like valid possibility and we have anyway started handling nil now on.

Although I am assuming right now it not to be the case, because @spMohanty and @alkeshrails never setup Discourse in their local. But it will be good if we can confirm with them.

**Comment by spMohanty** [comment]
The issue arised in my cases, because my local dev setup was pointing to the staging discourse. And my local db had only users from the default seeds. So, based on the discourse responses, it wasn't able to find the said participants in the local db.

**Comment by skbly7** [comment]
But I don't believe Discourse API should be successful when DISCOURSE_API_KEY has value "REDUCTED" or did you set it up too?

**Comment by piotrekpasciak** [comment]
> The issue arised in my cases, because my local dev setup was pointing to the staging discourse. And my local db had only users from the default seeds. So, based on the discourse responses, it wasn't able to find the said participants in the local db.

This is exactly what I've explained in posts above.

**Comment by skbly7** [comment]
@piotrekpasciak's explanation above suffice the issue, and we have fixed it in #1264 issue. 
We can reopen this ticket if necessary later on.
