### ISSUE TITLE
the content menu on challenge overview is messing with the capitalization of items

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#1292]
<img width="305" alt="Screenshot 2020-03-29 at 17 17 48" src="https://user-images.githubusercontent.com/1581312/77853185-098d6e00-71e3-11ea-8377-4ad1c2652ef6.png">

The "introduction" has a capital I in the actual content !

**Comment by nemaniarjun** [comment]
The current code lowercases everything and capitalises the first letter of the text. Should I change it to all-uppercase or make it use whatever text the user gives?
