### ISSUE TITLE
Issue with DCRCL Page

### ISSUE THREAD

**Issue by sanjaypokkali** [AIcrowd/AIcrowd#1471]
In the DCRCL challenge page the dataset table over flows into the latest submissions table.

https://aicrowd-staging.herokuapp.com/challenges/dcrcl-default-of-credit-card-clients

![Capture](https://user-images.githubusercontent.com/45477782/82060212-b44ee280-96e4-11ea-93d7-e325eaae713a.JPG)

**Comment by skbly7** [comment]
Via #1492 

![image](https://user-images.githubusercontent.com/3490586/82432321-846d5980-9aad-11ea-9228-ad5b770640e6.png)

**Comment by sanjaypokkali** [comment]
Looks good!
