### ISSUE TITLE
Issue in challenge "NeurIPS 2020: Procgen Competition"

### ISSUE THREAD

**Issue by alkeshrails** [AIcrowd/AIcrowd#1523]
- 
<img width="668" alt="Screenshot 2020-06-05 at 11 09 21" src="https://user-images.githubusercontent.com/18612440/83869366-1a5de100-a74a-11ea-9bd5-dc39b4db335a.png">

**Comment by skbly7** [comment]
Hi, as part of this issue, let's just focus on rendering issue in website i.e. 4th point

The code block upon scroll has white background instead of black. (And also we need to change black color to something greyish)

**Comment by skbly7** [comment]
Looks like this is done by #1526, closing.
