### ISSUE TITLE
Use GitHub username instead of name in omniauth

### ISSUE THREAD

**Issue by jyotishp** [AIcrowd/AIcrowd#1683]
Right now, when a user logs in using omniauth, the username is populated from the GitHub name. Refer: https://github.com/AIcrowd/AIcrowd/blob/master/app/controllers/participants/omniauth_callbacks_controller.rb#L32

The GitHub username seems to be available as `nickname`. Refer: https://github.com/omniauth/omniauth-github/blob/master/lib/omniauth/strategies/github.rb#L30

The GitHub username should be used to populate the AIcrowd username.

**Comment by skbly7** [comment]
Fixed in #1748, we no longer reset the username for Github logins.
