### ISSUE TITLE
A better way for partcipants to publicly share their accomplishments

### ISSUE THREAD

**Issue by XCaellaX** [AIcrowd/AIcrowd#29]
_From @XCaellaX on July 27, 2018 12:09_

Automatically generate a protected "certificate of participation/rank" PDF at the end of challenge, that participants could download on their profile.

Should contain (open to discussion):
- crowdAI logo
- Challenge name
- Challenge URL
- Challenge dates (start/end)
- 2 liners explaining challenge task/problem?
- participant username/real name <- with option to switch between the two?
- rank in the challenge
- date
- signature/stamp of some form?

-> involve @jsnrynlds for designing it?

_Copied from original issue: crowdAI/crowdai#889_

**Comment by marcelsalathe** [comment]
Just changed the title to something more generic. I think a certificate is one good way, but not the only one. Probably best to brainstorm this, but I agree that this is a high priority issue. Perhaps we can do some easy things quite quickly, and PDF generation later on...

**Comment by marcelsalathe** [comment]
During a challenge - ie at any time; vs final leaderboard

**Comment by spMohanty** [comment]
Related to https://github.com/AICrowd/AIcrowd/issues/372
