### ISSUE TITLE
A site wide reputation score

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#372]
We have to implement a site wide reputation score, which gets affected by participation in competitions, rank on leaderboards, effect of comments (number of views/likes, etc) and everything else we can think of. We will store a time series of how the score evolved over time.

**Comment by mridulnagpal** [comment]
Discussion:

Problems: 
1) Sparse Data
2) Longer challenges
3) Drift between top scorers and low scorers
4) Engage more users

Potential Solutions:
1) Get leaderboard positions on a weekly or bi-weekly basis (To solve the problem of longer challenges)
2) Add a decay to top scorers increment in rating (To avoid the drift between top and low scorers)
3) Add badges and additional perks which affect rating (Optional) (To engage more users)

References:
1) https://community.topcoder.com/longcontest/?module=Static&d1=support&d2=ratings
2) https://trueskill.org/

**Comment by nemaniarjun** [comment]
@mridulnagpal  nudge!
