### ISSUE TITLE
rendering issues in music challenge

### ISSUE THREAD

**Issue by marcelsalathe** [AICrowd/AIcrowd#415]
_From @marcelsalathe on November 26, 2017 11:03_

This looks wrong:

<img width="708" alt="screen shot 2017-11-26 at 12 02 43" src="https://user-images.githubusercontent.com/215057/33239399-d1d7e98c-d2a1-11e7-832a-29c58c4ee724.png">

_Copied from original issue: crowdAI/crowdai#448_

**Comment by spMohanty** [comment]
The correct syntax should be : `$ \mu $` but when I do it, I do not see anything at all.
Could be a CSS issue of how mathjax blocks are rendered ?

**Comment by spMohanty** [comment]
Okay, turns out, its probably an issue with the `Preview` tab.
I was using it to check how it will appear, and now when I updated the content disregarding the `Preview` output, it renders correctly on the main page.

**Comment by spMohanty** [comment]
The leaderboard headers do not render properly though.
Check the parts where usually we have "Score" and the "Secondary Score" headers.

**Comment by spMohanty** [comment]
<img width="917" alt="screen shot 2017-11-27 at 14 43 35" src="https://user-images.githubusercontent.com/1581312/33269545-633bbe96-d381-11e7-939f-de374c76ea97.png">

I have this already configured :-?
