### ISSUE TITLE
Update the Winners section for all the challenges 

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#491]
_From @spMohanty on March 12, 2018 14:42_

In the challenge edit page, there should be a "Winners" tab, where you can list the winners of the completed challenges, and a small section of the prizes they received etc

_Copied from original issue: crowdAI/crowdai#575_

**Comment by XCaellaX** [comment]
Is there a list of previous winners for all the completed Challenges?

**Comment by spMohanty** [comment]
@XCaellaX : We usually just put up a post in the discussion forum announcing the winners. A good example for the content that should go in the Winners section is this : https://www.crowdai.org/topics/official-results-we-have-a-winner/discussion

But for other challenges we can just start with listing down the winner names (top-3) in most cases from the Leaderboard.
