### ISSUE TITLE
need to change the importance algorithm

### ISSUE THREAD

**Issue by marcelsalathe** [AICrowd/AIcrowd#523]
_From @marcelsalathe on March 22, 2018 08:19_

Our current home page shows three challenges that have ended, while there are multiple ones that are currently running. This makes no sense and it's difficult to market crowdAI when all we show are past challenges. What is the current algorithm?

_Copied from original issue: crowdAI/crowdai#629_

**Comment by spMohanty** [comment]
I would also reference this issue : https://github.com/crowdAI/crowdai/issues/576

Where we wanted to use “participation” as one of the criterias for sorting ! We would want to bubble up all the challenges with a high participation.

**Comment by spMohanty** [comment]
Sounds good! But challenge status still gets a priority nevertheless, so running challenges get a priority.

**Comment by marcelsalathe** [comment]
Agreed.
