### ISSUE TITLE
Only allow sensible usernames 

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#645]
Currently the sign up page asks for a "Display Name" which seems to be used internally.  This can have spaces, etc.

We should let users instead choose a sensible username which acts as an online handle.
Existing guidelines of what an online handle should be like, should apply here.

**Comment by mridulnagpal** [comment]
@spMohanty Online standards for TopCoder are -
1) Should be between 2-15 characters
2) Can contain letters, numbers and these characters -_.{}[]

Should I proceed with this, or you have something else in mind?
