### ISSUE TITLE
Dataset message/announcements

### ISSUE THREAD

**Issue by XCaellaX** [AICrowd/AIcrowd#660]
_From @XCaellaX on July 17, 2018 14:27_

Would be nice to be able to display a message when challenge doesn't have a Dataset to redirect participants to GitHub repos for example.

Something like #783 would be perfect!

_Copied from original issue: crowdAI/crowdai#883_

**Comment by spMohanty** [comment]
In the meantime, should we simply upload a single page PDF with a link to the respective starter kits ?
