### ISSUE TITLE
Add a link to gitlab.aicrowd.com

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#763]
Add a link to gitlab.aicrowd.com on the homepage/navigation-menu.

@jsnrynlds : Gitlab.aicrowd.com is the place where all the user submitted code will reside. Do you have any suggesstions of where should this be better featured ?

This will be one of the core features of AIcrowd, and we want to encourage users to hangout there a lot !

**Comment by nemaniarjun** [comment]
@spMohanty Its there in the connect section in the footer, want to add it somewhere else too?

**Comment by jsnrynlds** [comment]
Were we also going to add it to the 'More' dropdown in `app-header`?

**Comment by spMohanty** [comment]
@nemaniarjun : Yes, we should add it in the footed, and also in the More drop down as suggested by @jsnrynlds . I will let you guys make the final decision on this.

**Comment by nemaniarjun** [comment]
@jsnrynlds We already have it in the footer, lets add it to the 'More' dropdown too, as the footer might not get as much attention.

**Comment by nemaniarjun** [comment]
Closing for aicrowd/AIcrowd-Design/issues/111
