### ISSUE TITLE
Username regex improvement, make alphabet compulsory

### ISSUE THREAD

**Issue by skbly7** [AICrowd/AIcrowd#767]
Username regex exist after #645 but it still allow usernames like "12345" i.e. all numbers. We should try not to have this in system, because usernames in that case can be confused with user_id. 

Example:
https://www.crowdai.org/participants/11411
https://www.crowdai.org/participants/12345

11411 is id and 12345 is username but codebase might be doing `WHERE id=value or username=value` and it may cause weird loopholes. 

Hence, I would like to propose username should always start with alphabet and/or at least have one alphabet.

**Comment by mridulnagpal** [comment]
This is done in #768
