### ISSUE TITLE
Add featured attribute to challenges

### ISSUE THREAD

**Issue by mridulnagpal** [AIcrowd/AIcrowd#777]
Add featured attribute to challenges which could be changed in the reordering service by admin

**Comment by nemaniarjun** [comment]
@mridulnagpal @spMohanty Do we still need this? we are using `.order(featured_sequence: :desc)` and it should work for what we want to do.

**Comment by spMohanty** [comment]
@nemaniarjun : I think we can get around by not adding a new attribute. But having a better interface to order the challenges ? I remember @mridulnagpal  did something around that, but couldnt find the interface when I quickly looked at the Admin interface right now.
