### ISSUE TITLE
Challenge card pictures should have the correct aspect ratio

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#787]
Jason confirms that challenge card pictures should be 16:9 , we have to figure out a way for them to be the correct aspect ratio. (Either crop them, or in the short term, only accept images of the correct aspect ratio)

**Comment by nemaniarjun** [comment]
The image has to be 16:9 or the card has to 16:9?

**Comment by spMohanty** [comment]
@nemaniarjun : the image has to be 16:9

**Comment by nemaniarjun** [comment]
Tried for an hour, I cant css :P
