### ISSUE TITLE
Challenge Export functionality

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#788]
We need a functionality to "export" a challenge, and then easily "import" the said challenge.
This will both help in cloning challenges in the future, and also to help interested challenge organizers (from crowdAI) to migrate their challenge content to AIcrowd

As a first step, we simply focus on the challenge specific content, and not anything that has a reference to the individual user.

**Comment by skbly7** [comment]
Lets focus on only database related things in this export/import functionality on first go (i.e. no image, etc blobs) which can form `json` file easily. (i.e. text, boolean, and similar information types)

This include to include:
- challenge model.
- challenge rounds model.
- rules model.
- partner model. (extended)
- any other association with challenge model (extended)

**Comment by skbly7** [comment]
@nemaniarjun can check in case any of migration export script can help our purpose here

**Comment by skbly7** [comment]
Export/Import buttons will be added in Admin tab

**Comment by piotrekpasciak** [comment]
Challenge associations:
Challenge Import:

Challenge Associations (association_name => table_name):
slugs => friendly_id_slugs
organizer => organizers
clef_task => clef_tasks
dataset_files => dataset_files
submission_file_definitions => submission_file_definitions
challenge_partners => challenge_partners
challenge_rules => challenge_rules
challenge_participants => challenge_participants
submissions => submissions
votes => votes
follows => follows
challenge_rounds => challenge_rounds
invitations => invitations
teams => teams
leaderboards => leaderboards (materialised view)
ongoing_leaderboards => ongoing_leaderboards (materialised view)
participant_challenges => participant_challenges (materialised view)
participant_challenge_counts => participant_challenge_counts (materialised view)
challenge_registrations => challenge_registrations (materialised view)
challenge_organizer_participants => challenge_organizer_participants (materialised view)
challenge_round_summaries => challenge_round_summaries (materialised view)

**Comment by piotrekpasciak** [comment]
Challenge fields:
    t.integer "organizer_id"
    t.string "challenge"
    t.string "status_cd", default: "draft"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "tagline"
    t.string "primary_sort_order_cd", default: "ascending"
    t.string "secondary_sort_order_cd", default: "not_used"
    t.boolean "perpetual_challenge", default: false
    t.string "answer_file_s3_key"
    t.integer "page_views", default: 0
    t.integer "participant_count", default: 0
    t.integer "submissions_count", default: 0
    t.string "score_title"
    t.string "score_secondary_title"
    t.string "slug"
    t.string "submission_license"
    t.boolean "api_required", default: false
    t.boolean "media_on_leaderboard", default: false
    t.string "challenge_client_name"
    t.boolean "online_grading", default: true
    t.integer "vote_count", default: 0
    t.text "description_markdown"
    t.text "description"
    t.text "evaluation_markdown"
    t.text "evaluation"
    t.text "rules_markdown"
    t.text "rules"
    t.text "prizes_markdown"
    t.text "prizes"
    t.text "resources_markdown"
    t.text "resources"
    t.text "submission_instructions_markdown"
    t.text "submission_instructions"
    t.text "license_markdown"
    t.text "license"
    t.text "dataset_description_markdown"
    t.text "dataset_description"
    t.string "image_file"
    t.integer "featured_sequence", default: 0
    t.boolean "dynamic_content_flag", default: false
    t.text "dynamic_content"
    t.string "dynamic_content_tab"
    t.text "winner_description_markdown"
    t.text "winner_description"
    t.boolean "winners_tab_active", default: false
    t.bigint "clef_task_id"
    t.boolean "clef_challenge", default: false
    t.boolean "submissions_page"
    t.boolean "private_challenge", default: false
    t.boolean "show_leaderboard", default: true
    t.string "grader_identifier"
    t.boolean "online_submissions", default: false
    t.boolean "grader_logs", default: false
    t.boolean "require_registration", default: false
    t.boolean "grading_history", default: false
    t.boolean "post_challenge_submissions", default: false
    t.boolean "submissions_downloadable", default: false
    t.text "dataset_note_markdown"
    t.text "dataset_note"
    t.boolean "discussions_visible", default: true
    t.boolean "require_toc_acceptance", default: false
    t.string "toc_acceptance_text"
    t.text "toc_acceptance_instructions"
    t.text "toc_acceptance_instructions_markdown"
    t.boolean "toc_accordion", default: false
    t.string "dynamic_content_url"
    t.string "prize_cash"
    t.integer "prize_travel"
    t.integer "prize_academic"
    t.string "prize_misc"
    t.integer "discourse_category_id"
    t.boolean "latest_submission", default: false
    t.string "other_scores_fieldnames"
    t.boolean "teams_allowed", default: true, null: false
    t.integer "max_team_participants", default: 5
    t.integer "team_freeze_seconds_before_end", default: 604800
    t.boolean "hidden_challenge", default: false, null: false
    t.datetime "team_freeze_time"

**Comment by piotrekpasciak** [comment]
@skbly7 @spMohanty 
Are you sure you want to allow Export and Import all associations and fields above?

I strongly recommend white listing of both fields and associations.

**Comment by skbly7** [comment]
Hi @piotrekpasciak , 
Yes let's go with whitelist, many of association/fields don't make sense if someone exports. 
But I would like to keep the whitelisted fields/association defined at a single place (array or something), so we can just edit in one go when we want to add/remove anything in the future. And same array should be deriving export/import functionality, so they are compatible with each other always.

Associations good to export:
```
clef_task => clef_tasks
dataset_files => dataset_files
submission_file_definitions => submission_file_definitions
challenge_partners => challenge_partners
challenge_rules => challenge_rules
challenge_rounds => challenge_rounds
challenge_round_summaries => challenge_round_summaries (materialised view)
```

Challenge fields to export:
```
t.string "challenge"
t.string "status_cd", default: "draft"
t.string "tagline"
t.string "primary_sort_order_cd", default: "ascending"
t.string "secondary_sort_order_cd", default: "not_used"
t.boolean "perpetual_challenge", default: false
t.string "answer_file_s3_key"
t.string "score_title"
t.string "score_secondary_title"
t.string "slug"
t.string "submission_license"
t.boolean "api_required", default: false
t.boolean "media_on_leaderboard", default: false
t.string "challenge_client_name"
t.boolean "online_grading", default: true
t.text "description_markdown"
t.text "description"
t.text "evaluation_markdown"
t.text "evaluation"
t.text "rules_markdown"
t.text "rules"
t.text "prizes_markdown"
t.text "prizes"
t.text "resources_markdown"
t.text "resources"
t.text "submission_instructions_markdown"
t.text "submission_instructions"
t.text "license_markdown"
t.text "license"
t.text "dataset_description_markdown"
t.text "dataset_description"
t.string "image_file"
t.integer "featured_sequence", default: 0
t.boolean "dynamic_content_flag", default: false
t.text "dynamic_content"
t.string "dynamic_content_tab"
t.text "winner_description_markdown"
t.text "winner_description"
t.boolean "winners_tab_active", default: false
t.bigint "clef_task_id" (?, I assume it will be coming from association insert above)
t.boolean "clef_challenge", default: false
t.boolean "submissions_page"
t.boolean "private_challenge", default: false
t.boolean "show_leaderboard", default: true
t.string "grader_identifier"
t.boolean "online_submissions", default: false
t.boolean "grader_logs", default: false
t.boolean "require_registration", default: false
t.boolean "grading_history", default: false
t.boolean "post_challenge_submissions", default: false
t.boolean "submissions_downloadable", default: false
t.text "dataset_note_markdown"
t.text "dataset_note"
t.boolean "discussions_visible", default: true
t.boolean "require_toc_acceptance", default: false
t.string "toc_acceptance_text"
t.text "toc_acceptance_instructions"
t.text "toc_acceptance_instructions_markdown"
t.boolean "toc_accordion", default: false
t.string "dynamic_content_url"
t.string "prize_cash"
t.integer "prize_travel"
t.integer "prize_academic"
t.string "prize_misc"
t.boolean "latest_submission", default: false
t.string "other_scores_fieldnames"
t.boolean "teams_allowed", default: true, null: false
t.integer "max_team_participants", default: 5
t.integer "team_freeze_seconds_before_end", default: 604800
t.boolean "hidden_challenge", default: false, null: false
t.datetime "team_freeze_time"
```

Please export the images for example as base64 data or similar, so it can be imported later on.
I think export/import thing which we used during migration would be of help here, @nemaniarjun can you add relevant links for that codebase here?
