### ISSUE TITLE
Organizer name linked together with "By"

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#793]
On the individual challenge page, the organizer name is currently linked along with the "By".
<img width="355" alt="screen shot 2019-01-19 at 09 45 52" src="https://user-images.githubusercontent.com/1581312/51430359-1bcb4f80-1bcf-11e9-8742-6689fc3ae4de.png">

Ideally the link should only be for the Oragnizer name, and the "By" should not be linked at all.

**Comment by nemaniarjun** [comment]
Done

**Comment by spMohanty** [comment]
@nemaniarjun : Can you include the commit id to the issue ids, so they are all cross linked neatly.

**Comment by nemaniarjun** [comment]
I did include it :)
