### ISSUE TITLE
Login via crowdAI button has a weird on-hover color

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#812]
<img width="560" alt="screen shot 2019-01-30 at 22 36 06" src="https://user-images.githubusercontent.com/1581312/52014327-876ec000-24df-11e9-88f2-15fb9b1d412a.png">

**Comment by jsnrynlds** [comment]
@spMohanty What's the URL for the test site?

It's fine my end: https://aicrowd-design.netlify.com/template-account-login

cc @mridulnagpal

**Comment by mridulnagpal** [comment]
I think the old and new css/js are mixings, will have a look

**Comment by mridulnagpal** [comment]
@natejenkins The page we are using takes its CSS from https://maxcdn.bootstrapcdn.com/bootstrap/scss/mixins/_buttons.scss which is causing the darkening of the button, whereas the version on netlify only uses application.css, can we compile the assets such that we do not use those mixins?

**Comment by mridulnagpal** [comment]
The issue here is that @jsnrynlds is only loading bootstrap-grid and bootstrap-reboot whereas we were loading whole of bootstrap. Currently am excluding the whole bootstrap file and only loading grid and reboot files.

**Comment by mridulnagpal** [comment]
@spMohanty Issue resolved for now, but we have to keep in mind that we are only using bootstrap-grid and bootstrap-reboot
