### ISSUE TITLE
Add LaTeX support on discourse.aicrowd.com

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#823]
References : https://meta.discourse.org/t/discourse-math-plugin/65770

**Comment by skbly7** [comment]
I tested the plugin installation on staging discourse.
It looks like Discourse rebuild the whole docker image upon addition of plugin (AND put live instance down during the same 😞 )

Hence, plugin install will mean downtime for Discourse, what time will be good to do so?
Approximate time taken by Staging: 10 minutes

**Comment by spMohanty** [comment]
@skbly7 : i would suggest to get this done when is convenient for you, but by adding a banner, or a maintenance mode page stating that we have a 10 mins downtime for maintenance.

**Comment by skbly7** [comment]
The plugin is now live.
