### ISSUE TITLE
a DOT in the username breaks API calls

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#842]
So when a GET call like : `/api/participants/ABC.XYZ` happens
Then the `params` received here : https://github.com/AICrowd/AIcrowd/blob/master/app/controllers/api/participants_controller.rb#L9
Has `params[:id]` as just “ABC” instead of “ABC.XYZ”

Needs fixing of the rails routes to allow "." in the params.

**Comment by mridulnagpal** [comment]
@spMohanty Pushed the changes

**Comment by mridulnagpal** [comment]
@spMohanty I am not sure if this is resolved?
