### ISSUE TITLE
Submissions tab should be visible to anonymous users

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#844]

**Comment by mridulnagpal** [comment]
@spMohanty I can see the submissions tab here (https://www.aicrowd.com/challenges/mediqa-2019-recognizing-question-entailment-rqe) without logging in. Anything else left for this issue?

**Comment by spMohanty** [comment]
Cant access this page from a private window : https://www.aicrowd.com/challenges/mediqa-2019-recognizing-question-entailment-rqe/submissions

:/
