### ISSUE TITLE
Messed up rendering of some radio buttons

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#845]
![screen shot 2019-02-25 at 21 18 52](https://user-images.githubusercontent.com/1581312/53366059-08847000-3943-11e9-8b2b-cf4e76256a88.png)

Seen at : https://aicrowd-redesign.herokuapp.com/challenges/unity-obstacle-tower-challenge/submissions

**Comment by mridulnagpal** [comment]
@spMohanty This looks good here https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge/leaderboards
Is this one done?

**Comment by spMohanty** [comment]
I just opened the **submissions tab** in a private window, and still doesnt work : https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge/submissions

**Comment by spMohanty** [comment]
Yes, this is fixed.
