### ISSUE TITLE
Add sensible default values to challenge subfields

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#849]
Add sensible default values to challenge sub fields, so that a challenge acts out of the box after creating the challenge through the create submission button. 

- [ ] Challenge Round Submission Limits 
- [ ] Challenge Rules 
- [ ] Round Start, Round End 
- [ ] Round Enabled

**Comment by mridulnagpal** [comment]
@spMohanty Some clarifications are required for this

1) What should we set the round submission limit
2) We need to prepare a wiki for default challenge rules
3) Round start can be starting now and end in a few months. (Still not sure what to put here)
4) This can be false by default

**Comment by nemaniarjun** [comment]
https://github.com/AIcrowd/AIcrowd/issues/937

**Comment by nemaniarjun** [comment]
Parts 1 and 2 done in above commit.

**Comment by nemaniarjun** [comment]
@spMohanty Can you detail the defaults for each of the mentioned things? 
Including for the description field (Overview)

**Comment by spMohanty** [comment]
The default values would be : 


* What should we set the round submission limit
  - 5 / day
* We need to prepare a wiki for default challenge rules
  - Add "Place holder rules" with instructions on where to update the rules
* Round start can be starting now and end in a few months. (Still not sure what to put here)
  - Starting now and ending in 6 months is sensible
* Round Enabled : 
  - This can be false by default
* Overview 
  - "Placeholder Content : Please update this by going into Edit Challenge > Overview > Description"

@nemaniarjun : Let me know if you have any other questions.
