### ISSUE TITLE
Resources button acting weird in the redesign branch

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#850]
![screen shot 2019-02-28 at 20 10 29](https://user-images.githubusercontent.com/1581312/53591728-f6017500-3b94-11e9-8e1e-4349368a21c3.png)

**Comment by mridulnagpal** [comment]
Fixed

**Comment by mridulnagpal** [comment]
@spMohanty This one is done. Should we close this issue?

**Comment by spMohanty** [comment]
Yes
