### ISSUE TITLE
Prizes section on edit Challenge is rendered incorrectly

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#852]
![screen shot 2019-02-28 at 20 12 36](https://user-images.githubusercontent.com/1581312/53591830-3e209780-3b95-11e9-93ac-b2957b705f57.png)

**Comment by mridulnagpal** [comment]
Fixed

**Comment by mridulnagpal** [comment]
This one looks good on production as well. Should we close this as well?

**Comment by spMohanty** [comment]
Yes please
