### ISSUE TITLE
Bug in sign-up form

### ISSUE THREAD

**Issue by ffledgling** [AIcrowd/AIcrowd#854]
When attempting to sign-up, if a user incorrectly enters some piece of information that violates the form validation conditions (eg. username does not contain a letter, username > 15chars etc), then the form dies and cannot be used for submission even after fixing the errors in form. (The submit button gets greyed out and becomes unclickable). The page needs to be hard refreshed to sign up again correctly.

**Comment by nemaniarjun** [comment]
Can confirm still persists :(

**Comment by nemaniarjun** [comment]
Looks to be fixed.
