### ISSUE TITLE
Challenge Edit: Break into smaller Forms

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#860]
Breakdown tabs into separate forms that save separately.

**Comment by nemaniarjun** [comment]
Still needed?

**Comment by spMohanty** [comment]
@nemaniarjun : Yes, the challenge edit form is still quite buggy. I would keep this issue open.

**Comment by skbly7** [comment]
@nemaniarjun Can you help in breaking down this issue with remaining tasks?
