### ISSUE TITLE
Personal Data Download broken

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#861]
This is after we moved the disucssions etc to Discourse.

We have to clearly specify what would count as personal data that users can download.
Submissions+code on gitlab, discussions on discourse, etc etc.

**Comment by nemaniarjun** [comment]
@spMohanty Bump

**Comment by spMohanty** [comment]
@nemaniarjun : I think this is best dealt with in the v2.0 rewrite.
