### ISSUE TITLE
Score headings on leaderboard not matching reference fields in forms

### ISSUE THREAD

**Issue by sfwatergit** [AIcrowd/AIcrowd#862]
<img width="1154" alt="aicrowd___leaderboard" src="https://user-images.githubusercontent.com/1607349/53796953-09407780-3eea-11e9-8524-16c2b2024dd4.png">

1. The current score headings are nonsensical outside of an RL challenge. These should match the score title indicated on the overview tab when setting up/editing challenge. 

2. As a further suggestion, if a secondary score is not used and/or if media is not used, then it/they should not appear as columns on the leaderboard.

**Comment by nemaniarjun** [comment]
Reopening for discussion on point 2: was auto closed due to pushing a commit

**Comment by spMohanty** [comment]
Agree about point 2. 
Lets make the secondary score configurable (based on the presence or absence of a title)
and same about Media.
@nemaniarjun : Can you have a look at this ?
