### ISSUE TITLE
Homepage: Testimonial – Quotation marks and voucher position

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#864]
@spMohanty @marcelsalathe I noticed the first [testimonial on the homepage](https://www.aicrowd.com/) has quotation marks; the second doesn't. Don't have strong feelings as to whether we include these but we should be consistent.

Also, wondering if we really need to show the voucher's company/org position (e.g., Postdoctoral Researcher)? I was envisaging that the voucher's name and company/org would be sufficient.

**Comment by nemaniarjun** [comment]
@marcelsalathe @spMohanty inputs about the 2nd part? Do we include the position? I am updating both to have quotation marks right now. Can remove the position too if needed.
