### ISSUE TITLE
Sticky footer broken

### ISSUE THREAD

**Issue by jsnrynlds** [AICrowd/AIcrowd#865]
@mridulnagpal Creating a separate issue for this so it doesn't get lost.

The footer isn't sticking to the bottom because it's currently nested in <div class="content"> when it should be outside it.

**Comment by mridulnagpal** [comment]
Got it out of content div and pushed to master

**Comment by spMohanty** [comment]
@mridulnagpal : Please reference the commits by putting in the #<issue_number> in the commit message. This helps keeping things organized.

**Comment by mridulnagpal** [comment]
e48cc81
