### ISSUE TITLE
Challenge Overview: Update font-size incorrect

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#866]
This is due to text being wrapped in `<p>` tags. Can we remove these please?

<img width="826" alt="screenshot 2019-03-05 at 11 09 54" src="https://user-images.githubusercontent.com/1162939/53801518-5565d900-3f37-11e9-8030-d91d1b291a48.png">

**Comment by mridulnagpal** [comment]
@jsnrynlds We can't remove the <p> tag as it is rendered by the markdown to html conversion done by markdown editor. Can you make the changes in CSS. This type of <p> tags will always be embedded inside <div class="markdown-wrap"> tags

**Comment by jsnrynlds** [comment]
@mridulnagpal No problem – I've updated `_md-content.scss` instead.

https://github.com/AICrowd/AIcrowd-Design/commit/89c871a092d2a69a85e57fc1bab2a80b37fe5906

**Comment by nemaniarjun** [comment]
https://github.com/AIcrowd/AIcrowd/issues/931
