### ISSUE TITLE
Challenge Overview: Jump links not working correctly

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#868]
This has been pushed to design repo but not live site. See following:

I've added an additional heading for the first section (Introduction), as this was missing. This needs `.mt-0` applied to it.

Also, not sure if we want to use JS to apply `.active` to the active nav item or if there's a better way to do this? (I don't think `:target` will work for this as the nav items don't have IDs.)

**Comment by nemaniarjun** [comment]
https://github.com/AIcrowd/AIcrowd/issues/931

**Comment by nemaniarjun** [comment]
@jsnrynlds can you check the current implementation here: https://aicrowd-staging.herokuapp.com//organizers/unity-technologies/challenges/unity-obstacle-tower-challenge#dates

**Comment by nemaniarjun** [comment]
Reopen this issue if changes are needed.
