### ISSUE TITLE
Challenge Overview: Videos need .md-video applied to them

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#869]
@spMohanty Not sure who to assign this to.

Videos in Challenge Overviews need the class `.md-video` assigned to them.

<img width="722" alt="screenshot 2019-03-05 at 11 19 33" src="https://user-images.githubusercontent.com/1162939/53802032-ac1fe280-3f38-11e9-87d5-7e71938bf81a.png">

**Comment by nemaniarjun** [comment]
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/owKdLnCjy3o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

When I add `class="md-video"` to the above it renders like this:

![image](https://user-images.githubusercontent.com/15715894/56648481-10d9fc80-66a1-11e9-970d-9ed7a4ad6cfa.png)

**Comment by jsnrynlds** [comment]
My mistake @nemaniarjun. This actually needs to be wrapped in an additional wrapper: 

````
<div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
</div>
````

Also removed `.md-video` and replaced with `.embed-responsive` in `_md-content.scss`.

**Comment by nemaniarjun** [comment]
Verified in the new css. Closing.
