### ISSUE TITLE
Challenge Leaderboard: Load more button (visually) broken

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#870]
There's a phantom grey background and spacing is wrong here:

<img width="1328" alt="screenshot 2019-03-05 at 11 32 09" src="https://user-images.githubusercontent.com/1162939/53802744-8562ab80-3f3a-11e9-8c84-d9382864774a.png">

See https://aicrowd-design.netlify.com/template-challenge-leaderboard for how this should look/be positioned.

**Comment by nemaniarjun** [comment]
Hey @jsnrynlds, so I fixed the spacing issue in the above commits, but the black background thing is caused by the following:

We have the html as follows:"

```
div.load-more
     a
          button
```
the following css causes this issue:

```
.load-more a {
...
height: 80px;
...
}
```

**Comment by nemaniarjun** [comment]
How do you suggest we tackle this? I think we have to render the button inside the a tag, if we have the a inside the button, then only the text would be clickable right?

**Comment by jsnrynlds** [comment]
Hi @nemaniarjun – the button classes can also be applied to `<a>` tags so we can simply change to the following:

```
<div class="load-more">
    <a class="btn btn-secondary btn-block" rel="next" data-remote="true" href="/challenges/unity-obstacle-tower-challenge/leaderboards?page=2">Load more</a>
</div>
```

**Comment by nemaniarjun** [comment]
This is how it is rendered with your suggestion.
![image](https://user-images.githubusercontent.com/15715894/56650204-2dc3ff00-66a4-11e9-8c82-a1c902527048.png)

**Comment by jsnrynlds** [comment]
@nemaniarjun Okay, I think there's some discrepancy with the design repo or maybe a nesting issue because that works fine for me:

<img width="1700" alt="Screenshot 2019-04-24 at 13 34 53" src="https://user-images.githubusercontent.com/1162939/56659743-d159e300-6695-11e9-932c-88ac5e026427.png">

**Comment by nemaniarjun** [comment]
Can you try to edit the HTML using the browsers inspect tool and check once?

**Comment by jsnrynlds** [comment]
@nemaniarjun There's seems to be some additional CSS that's not in the design repo:

````
.load-more a {
    display: block;
    color: rgba(0,0,0,0.87);
    font-size: 14px;
    line-height: 80px;
    height: 80px;
    transition: 0.4s;
}
````

We can remove this.

**Comment by nemaniarjun** [comment]
Cool. Will do!

**Comment by jsnrynlds** [comment]
Thanks!
