### ISSUE TITLE
Challenge Participate/Terms: Not styled

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#871]
@spMohanty Not sure whose responsibility this is...

This page isn't currently styled: https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge/participation_terms/1

There is a design for it: https://aicrowd-design.netlify.com/template-challenge-participate-terms

**Comment by mridulnagpal** [comment]
@jsnrynlds Can you add styling for pointers and subheadings after pointers?

**Comment by jsnrynlds** [comment]
Sorry @mridulnagpal – what do you mean by pointers? Bullets?

**Comment by jsnrynlds** [comment]
Closing this as it's duplicated https://github.com/AIcrowd/AIcrowd/issues/876
