### ISSUE TITLE
Challenges: Phantom line/divider at bottom of page

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#872]
Not sure where this is coming from...

<img width="1371" alt="screenshot 2019-03-05 at 11 38 58" src="https://user-images.githubusercontent.com/1162939/53803031-58fb5f00-3f3b-11e9-8442-9bcefa2241ca.png">

https://www.aicrowd.com/challenges

**Comment by nemaniarjun** [comment]
Caused by `.section-pt-sm-pb-md` having a padding-bottom of 60px

**Comment by jsnrynlds** [comment]
@nemaniarjun Actually, I think this is caused by an empty `load-more` class.

**Comment by nemaniarjun** [comment]
I checked after removing that attribute from that class, removes the phantom line like I think we want?

You can check it out using the browser's inspect tool.

**Comment by jsnrynlds** [comment]
@nemaniarjun Yep, that works.

**Comment by nemaniarjun** [comment]
@jsnrynlds So we want to remove it or keep it? If you make the change in Aicrowd-Design, I will sync it with the main repo today or tomorrow, so this will get fixed.

**Comment by jsnrynlds** [comment]
@nemaniarjun Yes, let's remove it.

**Comment by nemaniarjun** [comment]
I assume the change has been made to the Design Repo?

**Comment by jsnrynlds** [comment]
No, there's a 'Load more' button in the design repo which we may use in the future when there are lots of challenges. Can we just comment it out/disable it for now?

**Comment by nemaniarjun** [comment]
My bad, I was thinking it was a css change, will fix this now.

**Comment by jsnrynlds** [comment]
Cool – thanks.
