### ISSUE TITLE
User profile: Sub-nav bar broken

### ISSUE THREAD

**Issue by jsnrynlds** [AICrowd/AIcrowd#873]
This only seems to be happening on the sub-nav bar on user profile pages (seems okay everywhere else).

<img width="668" alt="screenshot 2019-03-05 at 11 41 03" src="https://user-images.githubusercontent.com/1162939/53803199-e76fe080-3f3b-11e9-8adf-0257bdcc93f8.png">

**Comment by mridulnagpal** [comment]
Fixed and pushed
