### ISSUE TITLE
Challenge Participation Terms – Rebuild

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#876]
As pointed out by @marcelsalathe 

Example : https://www.aicrowd.com/challenges/uber-2019-ml-hackathon/challenge_rules/6

cc. @jsnrynlds  @bkDJ

**Comment by spMohanty** [comment]
My response to marcel (in context of some of the discussions with @bkDJ  yesterday) : 

"for all the UI related stuff, I am holding off a bit until some reorganization we started with DJ yesterday gets completed.
Once thats done, all of this stuff will be exactly according to Jason’s design, and there wont be any “corruptions” from the old design."

**Comment by jsnrynlds** [comment]
@spMohanty @marcelsalathe 

As mentioned previously [these are currently a bit of a mess](https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge/participation_terms/1). I'd created a template for this but it didn't take into account the complex indentation of different levels within ordered lists. 

I've now rebuilt this using the first two sections of the Unity challenge as an example (as I think this covers everything – let me know if it doesn't): https://aicrowd-design.netlify.com/template-challenge-participate-terms

I've included styles for a lower roman counter (`<ol class="type-lower-roman">`) and a lower latin counter (`<ol class="type-lower-latin">`). 

Changes made to `_md-content.scss`.

Not sure who to assign this to?

**Comment by jsnrynlds** [comment]
These styles can be used for the Terms of Use, too.

**Comment by spMohanty** [comment]
@mridulnagpal : Can you ensure that these changes are merged ?

**Comment by spMohanty** [comment]
@mridulnagpal : Nudge

**Comment by jsnrynlds** [comment]
@spMohanty @mridulnagpal @nemaniarjun Bump
