### ISSUE TITLE
Missing Challenges

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#880]
Bug report over email from a user.

```
Hi CrowdAI,

I have a link to Vizoom 2018 challenge, but that's not visible on the challenges list, even when looking "All" and "load more...".

Original: https://www.crowdai.org/challenges/vizdoom-2018

I'm wondering if there are also other challenges that are now effectively "lost"...

So, in case you didn't realize there are some challenges that are disconnected, I thought I'd let you know.
```

**Comment by nemaniarjun** [comment]
There doesn't to be any obvious bug in our code that points towards this. 
One edge case can be if an "organizer" is invited to a "Private Challenge" (by another organizer)

Code:
https://github.com/AICrowd/AIcrowd/blob/04d3ceecd7b6a843aa2b493535a8b1f4dbd8ac0b/app/policies/challenge_policy.rb#L130

**Comment by nemaniarjun** [comment]
@spMohanty Maybe we should close this. I dont think we have any missing challenges.

**Comment by mridulnagpal** [comment]
@spMohanty Any updates on this one?

**Comment by nemaniarjun** [comment]
Closing as no missing challenges found, will open if needed.
