### ISSUE TITLE
Private Challenge Invitations broken

### ISSUE THREAD

**Issue by spMohanty** [AICrowd/AIcrowd#881]

**Comment by spMohanty** [comment]
https://github.com/AICrowd/AIcrowd/commit/79ad0cf78b3ecd9e006c24b50f77f492bccd765b fixes this temporarily.

But styling is still not done correctly. 
The styling should be : https://aicrowd-design.netlify.com/template-challenge-edit-private-challenge

**Comment by mridulnagpal** [comment]
This is a repetition of #853
