### ISSUE TITLE
1 Academic Papers

### ISSUE THREAD

**Issue by marcelsalathe** [AIcrowd/AIcrowd#883]
Issue with pluralization in challenges:

<img width="363" alt="Screen Shot 2019-03-10 at 21 18 20" src="https://user-images.githubusercontent.com/215057/54090940-14782500-437a-11e9-9441-474827373ff2.png">

**Comment by spMohanty** [comment]
Note that in Academic papers, we dont want a number. But just want to say : "Authorship/Co-Authorship in Academic Papers"

**Comment by mridulnagpal** [comment]
@spMohanty Sounds good, should we pluralize "Travel Grants" or change it to something else?

**Comment by marcelsalathe** [comment]
Travel grants sounds good to me

**Comment by mridulnagpal** [comment]
Okay just changing  Academic Papers -> Authorship/Co-Authorship for now

**Comment by marcelsalathe** [comment]
Authorship/Co-Authorship in Academic Papers

**Comment by mridulnagpal** [comment]
@marcelsalathe Do we pluralize this then?

**Comment by mridulnagpal** [comment]
@marcelsalathe Okay so to be clear, there will be Authorship/Co-Authorship in Academic Papers on the card if a boolean is true?

**Comment by mridulnagpal** [comment]
Or its a text field where you can add any text?

**Comment by marcelsalathe** [comment]
I'd put Authorship/Co-Authorship in Academic Papers if boolean is true. @spMohanty?
