### ISSUE TITLE
Organizers Edit Page is not accessible

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#884]

**Comment by spMohanty** [comment]
Example : https://www.aicrowd.com/organizers/unity-technologies/

**Comment by spMohanty** [comment]
The invite members page is also broken : https://www.aicrowd.com/organizers/unity-technologies/members :/

**Comment by mridulnagpal** [comment]
There are currently 2 conditions for showing the edit organizer button

1) Participant should be an admin
2) Record.id == participant.organizer_id (where record is passed as NULL)

I am not sure if it worked earlier if the user was not an admin

@spMohanty Who all should be able to access the edit organizer page?

**Comment by spMohanty** [comment]
Yes, only admins, and participant should be a member of the organization. 
At the moment, because of the way organization membership is implemented, a participant can only be a member of a single organization. That has to change too at some point. But not a high priority.
