### ISSUE TITLE
Dropdown active state needs fixing

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#887]
<img width="306" alt="screenshot 2019-03-05 at 10 20 16 2" src="https://user-images.githubusercontent.com/1162939/53798563-65c68580-3f30-11e9-999a-716bf41f30d9.png">

**Comment by mridulnagpal** [comment]
@jsnrynlds Is this still open or fixed? I checked on the current design it looks good. Should we close the issue?

**Comment by jsnrynlds** [comment]
@mridulnagpal It's been fixed in the design repo (https://github.com/AICrowd/AIcrowd-Design/commit/5e7d57f95fc8946a3af7eecf9df8f0994a70ffd7) but not live yet.
