### ISSUE TITLE
Challenge: Time remaining badges

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#888]
@spMohanty @marcelsalathe Could we maybe change the text in these badges from 'Round X' to 'RX'?

<img width="490" alt="Screenshot 2019-03-12 at 08 41 00" src="https://user-images.githubusercontent.com/1162939/54186168-abd89780-44a2-11e9-8ed4-a6bc851775a9.png">

**Comment by marcelsalathe** [comment]
I would not do that as people wouldn't know what R1 means

**Comment by jsnrynlds** [comment]
@marcelsalathe Okay, fair enough, just feels like a lot of text for a badge. Maybe we could round off the hours (after all the end times for rounds is in the overview)?
