### ISSUE TITLE
Sub-nav bar – Buttons wrong size

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#889]
All buttons in the sub-nav bar need the class `btn-sm` applied to them. E.g:

````
<a class="btn btn-secondary btn-sm">Participate</a>
````

Also, I wasn't anticipating a scenario where there'd be two buttons here – could we add the class `ml-1` (margin-left) to the second button? Or I can add some CSS to handle this...

<img width="1328" alt="Screenshot 2019-03-12 at 08 46 12" src="https://user-images.githubusercontent.com/1162939/54186515-7d0ef100-44a3-11e9-918e-f3c30feddaf0.png">

@spMohanty Again, not sure who to assign this to?

**Comment by mridulnagpal** [comment]
@jsnrynlds Made the changes required, the new styling looks like this
![Screenshot from 2019-03-17 02-43-37](https://user-images.githubusercontent.com/22350740/54466534-2c024400-47a6-11e9-82e0-6fe679fe1c24.png)

**Comment by jsnrynlds** [comment]
Great, thanks @mridulnagpal. Just to clarify we are doing the following?

> could we add the class ml-1 (margin-left) to the second button?

**Comment by spMohanty** [comment]
@jsnrynlds : Yes we are.

**Comment by mridulnagpal** [comment]
Yes we are using margin left class
