### ISSUE TITLE
Tooltips not working sitewide in the new design

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#894]

**Comment by mridulnagpal** [comment]
Can you give some sort of examples for this?

**Comment by nemaniarjun** [comment]
@spMohanty are you sure about this one? Tooltips at https://www.aicrowd.com/challenges/neurips-2019-minerl-competition seem to be working.

**Comment by spMohanty** [comment]
@nemaniarjun : You are right. Closing this issue.
