### ISSUE TITLE
On mobile, latest users don't show

### ISSUE THREAD

**Issue by marcelsalathe** [AIcrowd/AIcrowd#898]
<img width="422" alt="Screen Shot 2019-03-19 at 17 55 29" src="https://user-images.githubusercontent.com/215057/54625825-4d965080-4a70-11e9-8a42-f4af0a951d05.png">

Seems to be a problem with CSS as it is the same on Netlify - @jsnrynlds?

**Comment by jsnrynlds** [comment]
@marcelsalathe @mridulnagpal Fixed now – pushed to design repo: https://github.com/AIcrowd/AIcrowd-Design/commit/4d8f7f7145fed4aa268b059abd97f62417be02c2

I think we were going to previously hide this @mobile but for some reason only the content was being hidden (and not the heading also).

**Comment by jsnrynlds** [comment]
@mridulnagpal Not sure if this one slipped through the net?

**Comment by mridulnagpal** [comment]
@jsnrynlds @marcelsalathe Pushed a fix
