### ISSUE TITLE
Blog posts need a slug

### ISSUE THREAD

**Issue by marcelsalathe** [AIcrowd/AIcrowd#900]
This is not a cool URL for SEO:
https://www.aicrowd.com/blogs/1

we should have a definable slug, like in success stories.

**Comment by mridulnagpal** [comment]
b46fc414a3aaafdfac2dd8e1f9bb55f009dfa541

**Comment by spMohanty** [comment]
@mridulnagpal : Can you please add tests too ?

**Comment by nemaniarjun** [comment]
@mridulnagpal please check the tests

**Comment by nemaniarjun** [comment]
Test added, issue closed.
