### ISSUE TITLE
Success Story: Text width

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#901]
I think the pages look better with "justified" alignment. 

@jsnrynlds : What do you think ?

With jusitified alignment : 
<img width="1150" alt="Screenshot 2019-03-24 at 16 51 03" src="https://user-images.githubusercontent.com/1581312/54881922-4fd42280-4e55-11e9-9d9c-b530bcd428e3.png">

Without jusitified alignment : 

<img width="1078" alt="Screenshot 2019-03-24 at 16 51 26" src="https://user-images.githubusercontent.com/1581312/54881916-477be780-4e55-11e9-8e10-b7f82a31908c.png">

====
Also, on my screen, the actual content seems to only occupy a quarter of the page width. Not sure if that is intended or not.

**Comment by mridulnagpal** [comment]
Done
