### ISSUE TITLE
Fix Participant Counts in a Challenge

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#903]
The total number of participants in a challenge should be the **Set** of participants who have agreed to **any version** of the challenge rules.
(and not just the latest version of challenge rules)

**Comment by spMohanty** [comment]
This should be updated : https://github.com/AIcrowd/AIcrowd/blob/master/app/jobs/update_challenge_stats_job.rb#L22

**Comment by mridulnagpal** [comment]
@spMohanty This is done right?

**Comment by spMohanty** [comment]
Yes.
