### ISSUE TITLE
Additional Checkbox rendering messed up in Challenge Rules 

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#907]
<img width="1130" alt="Screenshot 2019-03-29 at 22 24 15" src="https://user-images.githubusercontent.com/1581312/55263482-75a46180-5271-11e9-9b49-561e5be33ad4.png">

The html from kramdown comes wrapped up in a `<p>` tag, which is causing some issues.
And finally, the checkbox and the label do not show up on the same line.

**Comment by nemaniarjun** [comment]
Still needed after @jsnrynlds 's new css?

**Comment by nemaniarjun** [comment]
Please verify with the CSS on aicrowd-redesign, looks fine to me.

**Comment by nemaniarjun** [comment]
Verified and closing.
