### ISSUE TITLE
Reduce login confusion

### ISSUE THREAD

**Issue by bkDJ** [AIcrowd/AIcrowd#910]
- When on login page, the header still has a "Log in" button. Possible solutions:
  - [ ] remove it
  - [ ] change it to "Sign up"

- When on login screen looking to create an account, the "Sign up" button is quite a ways below all the other options in the "Can't log in?" section. Possible solutions:
  - [x] Make a "Sign up" link in the "Can't log in?" section
  - [ ] Reduce spacing/`hr` between "Can't log in?" and "Not registered?" sections

See https://aicrowd-design.netlify.com/template-account-login

**Comment by jsnrynlds** [comment]
Hi @bkDJ – re 'Log in' button, I'm not sure removing this/changing it is a good idea. I've not noticed this behaviour on other platforms and users will know that the button in the header is detached from the content below.

Good call on the 'Sign up' link. I've added this to the 'Can't log in' section instead.
