### ISSUE TITLE
Add option to sort leaderboard by latest submission score(s)

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#912]

**Comment by mridulnagpal** [comment]
@jsnrynlds Can you add a button/styling to do this, I have the backend ready

**Comment by spMohanty** [comment]
@mridulnagpal : Why should there be more styling changes ? Shouldnt it be just the order of sorting ?

**Comment by nemaniarjun** [comment]
I think he means that there is no button to change the sorting.
I think its best if we change sorting when the user clicks on a respective header.

**Comment by spMohanty** [comment]
@nemaniarjun : The sorting order is currently decided in the Challenge Edit window. The current options available are Ascending and Descending. We just want another option called "Latest".

If we can have a setup where all the three sorting orders are computed, and users have the ability to see all the three leaderboards (for all the rounds of the competition), that would be great to have, but not sure if its a necessity !

**Comment by nemaniarjun** [comment]
If we do that way, I would say it would be easier/simpler to do using frontend js rather than backend ruby.

**Comment by spMohanty** [comment]
@nemaniarjun : front javascript would get really complicated when you take into account thousands of submissions, and pagination.

**Comment by jsnrynlds** [comment]
Let me know if you need me to look at anything related to this in terms of design.

**Comment by mridulnagpal** [comment]
@spMohanty Pushed a fix 9939d2ad4e85343174352b4fb57432627e134f74
