### ISSUE TITLE
webpack-dev-server being installed on production

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#915]
...and it shouldnt be installed on production

**Comment by nemaniarjun** [comment]
https://devcenter.heroku.com/changelog-items/1376

**Comment by nemaniarjun** [comment]
https://devcenter.heroku.com/articles/nodejs-support#package-installation

**Comment by nemaniarjun** [comment]
we will have to set 
`NPM_CONFIG_PRODUCTION=true` and 
`YARN_PRODUCTION=true`

on staging (where the build step happens) and on production (cause it wont hurt to do that)

**Comment by nemaniarjun** [comment]
Done on staging.

**Comment by nemaniarjun** [comment]
Done on production too.

**Comment by nemaniarjun** [comment]
Heroku will run the build step on our next push to master, then is should install the DevDependencies in package.json. 
I am also pushing a change to package.json, changing the name to aicrowd and author to AIcrowd Rails Author <hello@aicrowd.com>

**Comment by nemaniarjun** [comment]
```       
-----> Pruning devDependencies
       Skipping because NPM_CONFIG_PRODUCTION is 'true'
```

**Comment by nemaniarjun** [comment]
>> heroku run -a aicrowd-staging 'yarn list|grep webpack-dev'

Running yarn list|grep webpack-dev on ⬢ aicrowd-staging... up, run.8344 (Hobby)
│  ├─ webpack-dev-server@2.9.4
├─ webpack-dev-middleware@1.12.2
├─ webpack-dev-server@2.9.4
│  ├─ webpack-dev-middleware@^1.11.0

**Comment by nemaniarjun** [comment]
Part of : https://github.com/AIcrowd/AIcrowd/issues/1146
