### ISSUE TITLE
Display meta parameters on submission details page

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#918]
the meta parameter is a hash which lets the evaluators set arbitrary key values. 

The submission details page should show the key-value pairs rendered as a table.
Any key starting with "private" should be ignored. 

Additionally, the link to the submission file should be made available as a pre-signed link for the participant himself, and the admins and the challenge organizers.

**Comment by spMohanty** [comment]
The submission description should also be made available only to the participant himself and the admins and the challenge organizers

**Comment by mridulnagpal** [comment]
@spMohanty The key and value are now being displayed on submission details page but we need styling for that, @jsnrynlds can you add a table styling for key value pairs to the submission details page here (https://aicrowd-design.netlify.com/template-challenge-submission-detail)

**Comment by mridulnagpal** [comment]
@spMohanty Did not get this "Additionally, the link to the submission file should be made available as a pre-signed link for the participant himself, and the admins and the challenge organizers."

**Comment by spMohanty** [comment]
The participants / organizers might want to download the actual submission
file they submitted.

So we should include a link to the submission file.

Mohanty

**Comment by mridulnagpal** [comment]
Cool got it

**Comment by mridulnagpal** [comment]
@spMohanty Currently key value looks like this 
![Screenshot from 2019-04-19 17-01-31](https://user-images.githubusercontent.com/22350740/56422419-d6e5b080-62c4-11e9-9c28-edadcaf54cfc.png)

Also when key starts with private its not displayed

**Comment by nemaniarjun** [comment]
@spMohanty I think this is done.
