### ISSUE TITLE
Delete Participant breaks for OAuth users

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#919]

**Comment by nemaniarjun** [comment]
More details on this one?

**Comment by spMohanty** [comment]
Try deleting @mridulnagpal ‘s account on production or staging.

**Comment by nemaniarjun** [comment]
I pushed a fix that should make it able to delete him.

**Comment by nemaniarjun** [comment]
I deleted him

**Comment by nemaniarjun** [comment]
As far as I understand this is not an issue? Please confirm.
