### ISSUE TITLE
Markdown content: Increase line-height for lists

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#945]
Line-height for lists (`<ul>`) differs from paragraph text.

**Comment by nemaniarjun** [comment]
Can this be closed? Please verify after checking https://aicrowd-redesign.herokuapp.com/ !

**Comment by jsnrynlds** [comment]
@nemaniarjun I think so. [Looks fine](https://aicrowd-redesign.herokuapp.com/challenges/unity-obstacle-tower-challenge) to me.
