### ISSUE TITLE
Submission detail – Tidy Meta Parameters & video

### ISSUE THREAD

**Issue by jsnrynlds** [AIcrowd/AIcrowd#953]
https://www.aicrowd.com/challenges/8/submissions/5321

**Comment by nemaniarjun** [comment]
@jsnrynlds I dont see any difference in the html of the one sent by you and the current implementation. 
Except the meta params, which I am against changing only for this challenge.

**Comment by nemaniarjun** [comment]
I will update the css later.

**Comment by jsnrynlds** [comment]
Hey @nemaniarjun – it looks good to me.

Can we remove the empty `<p>` tags below the submission title as it's resulting in a large whitespace? https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge/submissions/5349

**Comment by nemaniarjun** [comment]
I can, but I dont think that is the reason for the empty space. Can you recheck?

**Comment by nemaniarjun** [comment]
The majority of the space is caused by `mt-5`

**Comment by nemaniarjun** [comment]
The empty p-tag is space for entry description. 

With Description with mt-5:
![image](https://user-images.githubusercontent.com/15715894/58157201-6f40cd80-7c95-11e9-9dcb-c1c32625580a.png)

With Description without mt-5: 
![image](https://user-images.githubusercontent.com/15715894/58157285-97303100-7c95-11e9-9cde-32141b3c14af.png)

So should I remove the mt-5? (I will conditional the empty tags)
