### ISSUE TITLE
Minor styling issues on challenge terms page

### ISSUE THREAD

**Issue by seanfcarroll** [AIcrowd/AIcrowd#961]
Just needs some padding.

<img width="549" alt="Screenshot 2019-06-01 at 16 48 03" src="https://user-images.githubusercontent.com/11340230/58750025-18a17380-848d-11e9-9a7d-abdaa074c933.png">

**Comment by nemaniarjun** [comment]
We have an upcoming CSS sync with the design repo, which reminds me I am still waiting for a branch push by @bkDJ  with some partial work for structuring the SASS properly.

**Comment by nemaniarjun** [comment]
Done with the merge.
