### ISSUE TITLE
Submissions by participants not showing up on leaderboard

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#965]
Discussion on Discourse: https://discourse.aicrowd.com/t/successful-submissions-do-not-appear-on-the-leaderboard/1057

List of submissions : https://www.aicrowd.com/admin/challenges/unity-obstacle-tower-challenge/submissions

**Comment by spMohanty** [comment]
Update, the leaderboard was computed correctly, when I manually ran : 
```
CalculateLeaderboardJob.perform_now(:challenge_round_id => REDACTED)
```

**Comment by seanfcarroll** [comment]
Leaderboard rebuild should be triggered on any save of a Submission (assuming it goes via ActiveRecord and not direct SQL).

https://github.com/AIcrowd/AIcrowd/blob/master/app/models/submission.rb#L59-L65

**Comment by nemaniarjun** [comment]
There dont seem to be any recent failed jobs on the sidekiq admin interface. 
The problem seems to be the queuing of these jobs. |

Holds for as well: https://github.com/AIcrowd/AIcrowd/issues/958

**Comment by nemaniarjun** [comment]
Are all the missing submissions made via the GitLab / API?
There could be a time gap between the "save" of a submission and the update where the status is changed from initiated to "graded".
We trigger the CalculateLeaderboard job on each save, not each time there is an update to an submission, we should maybe add it there too. 
https://github.com/AIcrowd/AIcrowd/blob/1e9a5e866538a015b752ea53a7169eaf19897432/app/models/submission.rb#L59-L65

**Comment by nemaniarjun** [comment]
`after_save runs both on create and update, but always after the more specific callbacks after_create and after_update, no matter the order in which the macro calls were executed.`
