### ISSUE TITLE
Fix sidekiq-unique-jobs configs to not pollute redis

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#967]
The [sidekiq-unique-jobs](https://github.com/AIcrowd/AIcrowd/issues/965) configs have to be properly adjusted to cleanup after they are done. Now they are leaving a lot of keys like : `uniquejobs:1dd6574deb769dd4057643a5f847977d:AVAILABLE` which end up clogging up the Sidekiq queue eventually.

This was the reason the leaderboard submissions were not showing up.

**Comment by nemaniarjun** [comment]
This was fixed in the update for sidekiq-unique-jobs, should not happen again.
