### ISSUE TITLE
Leaderboard message markdown is being rendered weird

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/AIcrowd#982]
<img width="828" alt="Screenshot 2019-07-21 at 14 54 44" src="https://user-images.githubusercontent.com/1581312/61590891-3d79b380-abbf-11e9-917b-b5942b995d4f.png">

https://www.aicrowd.com/challenges/neurips-2019-disentanglement-challenge/leaderboards

**Comment by nemaniarjun** [comment]
@jsnrynlds

**Comment by jsnrynlds** [comment]
@spMohanty @nemaniarjun 

I don't think it makes sense to use the `md-content` update boxout here (or anywhere else outside of markdown content). Maybe we can modify one of the alert boxes instead? I think this should be dismissible, too (i.e. close icon in top-right)? Does that sound okay?

**Comment by nemaniarjun** [comment]
I am against using this as an alert box.
The note renders markdown.

You keep the css /Html as you prefer.

But functionally makes no sense to dismiss it.

As it's supposed to hold information about how leaderboard is calculated.

**Comment by jsnrynlds** [comment]
Okay, I was envisaging that it would reappear on the next page load but I see your point.

So this needs to continue to be rendered using markdown?

**Comment by nemaniarjun** [comment]
Yes, according to me.

I assume that the math from kramdown will be useful for formulas.

Let's wait for Mohanty to see this.

**Comment by spMohanty** [comment]
Yeah, the content will be rendered using Kramdown.
And the note should also not be dismissivle. We usually use it to make
announcements specific to the leaderboard, or in some cases add warning
messages (ex : the computed leaderboard is only tentative, the final scores
will be updated on so and so date)

Cheers,
Mohanty

**Comment by jsnrynlds** [comment]
@spMohanty @nemaniarjun  Right, I've created a new class (`note`) within `_md-content.scss`. I think this is looking much better: https://aicrowd-design.netlify.com/template-challenge-leaderboard

Thoughts?

**Comment by nemaniarjun** [comment]
Looks great! Will integrate today itself!

**Comment by jsnrynlds** [comment]
Awesome, thanks @nemaniarjun
