### ISSUE TITLE
CSS problem: tooltips

### ISSUE THREAD

**Issue by bkDJ** [AIcrowd/AIcrowd#995]
We should be using [Bootstrap tooltips](https://getbootstrap.com/docs/4.0/components/tooltips/), but some CSS isn't working properly. Example:

![image](https://user-images.githubusercontent.com/6138914/63604202-7bf1fc00-c5cb-11e9-8aaa-072938d46cc6.png)

The text "This challenge is not running" should be in a popup (light text on dark background) above the "Create Team" button when hovering with mouse. Instead it appears far to the left.

**Comment by bkDJ** [comment]
Once this is working, then this line can be uncommented:

https://github.com/AIcrowd/AIcrowd/blob/9c4a8e6d73112011ba8e44b9e483d69baec03bc6/app/assets/javascripts/modules/tooltips.js#L2

**Comment by nemaniarjun** [comment]
It works for me on the redesign deploy without any issues. 
Without commenting the line. 
Will close if it works on prod :man_shrugging:
